// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const federatedConfig = {
    "google_client_id": "73521xxxxxxxxxxx455ftn4145u4ndkr941v.apps.googleusercontent.com",
    "amazon_client_id": "amzn1.application-oa2-client.a1xxxxxxx54a",
};


export default federatedConfig;
